apiVersion: v1
kind: Service
metadata:
  name: urlshorty-service
spec:
  type: NodePort # NodePort es f√°cil para probar en Minikube
  selector:
    app: urlshorty
  ports:
  - protocol: TCP
    port: 80       # Puerto expuesto por el servicio
    targetPort: 8080 # Puerto de tu contenedor (Spring Boot)